# -*- coding: utf-8 -*-
"""Automobile Data Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105fQ_0vi-UCADdxPxSViVa5cjn7zhH2n

# Automobile Data
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Machine Learning/automobile_data.csv'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_auto = pd.read_csv(file_path)

df_auto.head()

df_auto.shape

df_auto.columns

df_auto.dtypes

# check out the null values
df_auto.info()

df_auto.isnull().sum()

df_auto['num_of_doors'].unique()

# drop the null values
df_auto = df_auto.dropna()

df_auto.isnull().sum()

df_auto.shape

# average price
df_auto['price'].mean()

sns.boxplot(df_auto['price'])

df_auto.describe()

df_auto[df_auto['price'] == df_auto['price'].max()]

df_auto[df_auto['price'] == df_auto['price'].min()]

df_auto.groupby('make')['price'].mean()

#Create a bar chart showing the number of cars for each fuel type.
plt.figure(figsize=(5,4))
df_auto['fuel_type'].value_counts().plot(kind='bar')
plt.show()

#Create a bar chart showing the frequency of different body styles.
df_auto['body_style'].value_counts().plot(kind='bar')
plt.title('Frequency of Different Body Styles')
plt.xlabel('Body Style')
plt.ylabel('Frequency')
plt.show()

plt.hist(df_auto['price'], bins=20)
plt.title("Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

# create a scatter plot between horsepower and price
plt.scatter(df_auto['horsepower'], df_auto['price'])
plt.xlabel("Horsepower")
plt.ylabel("Price")
plt.title("Horsepower vs Price")
plt.show()

# create a scatter plot showing the relationship between engine size and price
plt.scatter(df_auto['engine_size'], df_auto['price'])
plt.xlabel("Engine Size")
plt.ylabel("Price")
plt.title("Engine Size vs Price")
plt.show()

#Create a scatter plot comparing city mileage and highway mileage.
plt.scatter(df_auto['city_mpg'], df_auto['highway_mpg'])
plt.xlabel("City MPG")
plt.ylabel("Highway MPG")
plt.title("City vs Highway Mileage")
plt.show()

# create a bar chart showing the average price of cars for each manufacturer
df_auto.groupby('make')['price'].mean().sort_values().plot(kind='bar')
plt.title("Average Price by Manufacturer")
plt.xlabel("Manufacturer")
plt.ylabel("Average Price")
plt.show()

#Create a bar chart showing average price by fuel type.
df_auto.groupby('fuel_type')['price'].mean().plot(kind='bar')
plt.title("Average Price by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Average Price")
plt.show()

# create a bar chart showing the top 10 highest priced cars
top10 = df_auto.sort_values(by='price', ascending=False).head(10)
plt.bar(top10['make'], top10['price'])
plt.title("Top 10 Most Expensive Cars")
plt.xlabel("Manufacturer")
plt.ylabel("Price")
plt.show()

#Create a line graph comparing city MPG and highway MPG.
plt.plot(df_auto['city_mpg'], label="City MPG")
plt.plot(df_auto['highway_mpg'], label="Highway MPG")

plt.legend()
plt.title("Mileage Comparison")
plt.show()